# practice_data.msg

## Fundamental field types
string string_data
bool bool_data
int32 int32_data
float64 float64_data
time time_data
duration duration_data

## Message types of other packages
std_msgs/String std_msgs_string
std_msgs/ColorRGBA std_msgs_colorrgba
std_msgs/Header std_msgs_header

geometry_msgs/Pose geometry_msgs_pose
geometry_msgs/Transform geometry_msgs_transform

basic_lecture/motor_data basic_lecture_motor_data
